INSERT OR IGNORE INTO stores (id, name, keywords, icon_path) VALUES
('4f', '4F', '4f,ff,4 f,f4,sklep4f,4ff,4-f,fourf,forf,4yf', 'assets/icons/4f.png'),
('action', 'Action', 'action,akcion,akcjon,akcionn,ation,akcion store,akcyn,akcn,aksyon', 'assets/icons/action.png'),
('apteka_codzienna', 'Apteka Codzienna', 'apteka codzienna,apteka,codzienna,apteka-codzienna,apteka codzi,apteka codz,apteka c,apteka cod,apteka dzienna,codz apteka', 'assets/icons/apteka-codzienna.png'),
('auchan', 'Auchan', 'auchan,auchan pl,auchanpolska,auchan market,auchan super,auch,auhan,auszan,auszan pl,auchan s', 'assets/icons/auchan.png'),
('bp', 'BP', 'bp,bp station,bp stacja,bp polska,stacja bp,benzin bp,bpp,bp gas,bp fuel,stacj bp', 'assets/icons/bp.png'),
('burger_king', 'Burger King', 'burger king,burgerking,b king,bking,burgr king,burg king,burgerk,burge king,bking polska,king burger', 'assets/icons/burger-king.png'),
('carrefour', 'Carrefour', 'carrefour,carfour,carrefur,carrefor,carre four,carrefor pl,carfur,carref,carrefourpolska,carefour', 'assets/icons/carrefour.png'),
('castorama', 'Castorama', 'castorama,castorama pl,castora,casto,castorama s,a castorama,castromama,castor,casto rama,castorma', 'assets/icons/castorama.png'),
('ccc', 'CCC', 'ccc,cc c,ccc pl,ccc s,cc store,c cc,cccshoes,ccc shoe,cccs,cccobuwie', 'assets/icons/ccc.png'),
('circle_k', 'Circle K', 'circle k,circlek,circl k,circl,k station,circlek pl,cirklk,cirkle k,circle gas,circl', 'assets/icons/circle-k.png'),
('cropp', 'Cropp', 'cropp,crop,croop,crop store,cropp town,crop pt,croop p,cropp pl,croppshop,cropp s', 'assets/icons/cropp.png'),
('decathlon', 'Decathlon', 'decathlon,decath,dekathlon,decathln,dekathlo,dekath,decathlo,decathl,decathlon pl,decath store', 'assets/icons/decathlon.png'),
('delikatesy_centrum', 'Delikatesy Centrum', 'delikatesy centrum,delikatesy,centrum,delikates centrum,delikatesy c,delikat centrum,delikat c,delicentrum,deli centrum,delicentr', 'assets/icons/delikatesy-centrum.png'),
('dino', 'Dino', 'dino,dino pl,dino polska,dino market,dino sklep,dino s,dino p,dyno,dinopol,dino sp', 'assets/icons/dino.png'),
('douglas', 'Douglas', 'douglas,dougl,douglas pl,douglas store,douglas p,douglas shop,dougls,douglaz,dougla,doglas', 'assets/icons/douglas.png'),
('doz', 'DOZ Apteka', 'doz,doz apteka,doz.pl,apteka doz,dozz,doz aptek,doz s,a doz,doz pharm,dozpharm', 'assets/icons/doz.png'),
('euro_rtv_agd', 'Euro RTV AGD', 'euro rtv agd,rtv agd,eurortv,agd euro,euroagd,rtveuro,rtveuroagd,rtv-euro,eurortv pl,rtv agd s', 'assets/icons/euro-rtv-agd.png'),
('hm', 'H&M', 'h&m,hm,h and m,h m,h-m,h n m,h m store,hmpl,hm s,hampm', 'assets/icons/h&m.png'),
('hebe', 'Hebe', 'hebe,hebe pl,hebe drogeria,hebe store,hebe s,hebe shop,hebee,hebe d,he be,hebe dro', 'assets/icons/hebe.png'),
('house', 'House', 'house,haus,house store,house pl,haus s,hauss,house shop,haus pl,house s,houes', 'assets/icons/house.png'),
('huzar', 'Huzar', 'huzar,huzar sp,huzar s,huzar gas,huzar stacja,huzar fuel,huzr,huzarr,huzarpl,huzr st', 'assets/icons/huzar.png'),
('ikea', 'IKEA', 'ikea,ikea pl,ikea store,ikea s,ikea polska,ikea shop,ikia,ikeea,ik a,ike', 'assets/icons/ikea.png'),
('kaufland', 'Kaufland', 'kaufland,kaufl,kaufland pl,kauf land,kauf,lidl kauf,kaufland s,kaufland sklep,kaufland polska,kauf pl', 'assets/icons/kaufland.png'),
('kfc', 'KFC', 'kfc,k f c,kf c,kf,kfcpl,kfc polska,kfc store,kfc s,kfc rest,kfcp', 'assets/icons/kfc.png'),
('lewiatan', 'Lewiatan', 'lewiatan,lewatan,lew,lewiata,lewiat,lewiatan pl,lewiatan s,lewiatan sklep,lewiatan polska,lewiatn', 'assets/icons/lewiatan.png'),
('lotos', 'Lotos', 'lotos,lotos s,lotos polska,stacja lotos,lotos station,lotos fuel,lotos oil,lotoss,lot,lotose,lotospl', 'assets/icons/lotos.png'),
('mcdonalds', 'McDonald’s', 'mcdonalds,mcd,mcdonald,macdonald,mc donald,makdonald,mcdo,mcdonlds,mcdonalds pl,mc don', 'assets/icons/mcdonalds.png'),
('media_expert', 'Media Expert', 'media expert,mediaexpert,mediaexp,media exp,mediaex,media exprt,mediaexprt,mediexpert,media expr,med expert', 'assets/icons/media-expert.png'),
('media_markt', 'Media Markt', 'media markt,mediamarkt,media mark,media mark store,media markt pl,mediamrkt,media mart,media mar,medimarkt,medimark', 'assets/icons/media-markt.png'),
('obi', 'OBI', 'obi,o b i,ob i,obbi,obii,obi pl,obi sklep,obi s,obi market,obi market pl', 'assets/icons/obi.png'),
('orlen', 'Orlen', 'orlen,pkn orlen,orlen stacja,orlen station,orlen fuel,orlen gas,orlen s,orlenpl,orlene,orl n', 'assets/icons/orlen.png'),
('reserved', 'Reserved', 'reserved,reserv,reserved pl,resrved,reservd,reservd pl,reserved s,reserve,resrve,resrvd', 'assets/icons/reserved.png'),
('shell', 'Shell', 'shell,shell pl,shell station,shell fuel,shel,schell,sh ell,shell s,shell gas,shellpol', 'assets/icons/shell.png'),
('sinsay', 'Sinsay', 'sinsay,sinsai,sinsy,sinsay pl,sinsai pl,sinsy pl,sinsay shop,sinsai shop,sinsay s,sinsai s', 'assets/icons/sinsay.png'),
('smyk', 'Smyk', 'smyk,smyk pl,smyk shop,smyk sklep,smik,smykk,smyk s,smyk store,smyk polska,smykpl', 'assets/icons/smyk.png'),
('stokrotka', 'Stokrotka', 'stokrotka,stokrotka pl,stokrotka s,stokrotka sklep,stokrot,stokro,stokrotk,stokrotka polska,stokrotka shop,stokrotka store', 'assets/icons/stokrotka.png'),
('super_pharm', 'Super-Pharm', 'super-pharm,super pharm,superpharm,superfarm,super farm,super pharm pl,superpharm pl,su pharm,su farm,super pharm s', 'assets/icons/super-pharm.png'),
('swiat_ksiazki', 'Świat Książki', 'swiat ksiazki,świat książki,swiat ksiazek,swiet ksiazki,swiatksiazki,swiat ks,ksiazki,ksiazek,sw ksiazki,sw książki', 'assets/icons/swiat-ksiazki.png'),
('tania_ksiazka', 'Tania Książka', 'tania ksiazka,taniaksiazka,tania-ksiazka,tania ks,t ksiazka,taniaks,tani ksiazki,tania ksi,tan ksiazka,tani ksia', 'assets/icons/tania-ksiazka.png'),
('x_com', 'X-kom', 'x-com,xcom,x kom,x-kom,xkom,xc om,xkom pl,xkom s,x-kom pl,xkomp', 'assets/icons/x-com.png');
